/**
 * College data extracted from DBMCI One_ College list - India.csv
 * Maps each state to its list of medical colleges.
 */

export const COLLEGES_BY_STATE: Record<string, string[]> = {
  "Andaman & Nicobar Islands": [
    "Andaman & Nicobar Islands Institute of Medical Sciences, Port Blair",
  ],
  "Andhra Pradesh": [
    "ACSR Government Medical College Nellore",
    "All India Institute of Medical Sciences, Mangalagiri, Vijayawada",
    "Alluri Sitaram Raju Academy of Medical Sciences, Eluru",
    "Andhra Medical College, Visakhapatnam",
    "Apollo Institute of Medical Sciences and Research, Chittoor",
    "Dr. P.S.I. Medical College , Chinoutpalli",
    "Fathima Instt. of Medical Sciences,Kadapa",
    "GITAM Institute of Medical Sciences and Research, Visakhapatnam",
    "GSL Medical College, Rajahmundry",
    "Gayathri Vidya Parishad Institute of Health Care & Medical Technology, Visakhapatnam",
    "Government Medical College, Ananthapuram",
    "Government Medical College, Eluru",
    "Government Medical College, Machilipatnam",
    "Government Medical College, Nandyal",
    "Government Medical College, Rajamahendravaram",
    "Government Medical College, Vizianagaram",
    "Government Siddhartha Medical College, Vijaywada",
    "Great Eastern Medical School and Hospital,Srikakulam",
    "Guntur Medical College, Guntur",
    "Katuri Medical College, Guntur",
    "Konaseema Institute of Medical Sciences & Research Foundation, Amalapuram",
    "Kurnool Medical College, Kurnool",
    "Maharajah Institute of Medical Sciences, Vizianagaram",
    "NRI Institute of Medical Sciences, Visakhapatnam",
    "NRI Medical College, Guntur",
    "Narayana Medical College, Nellore",
    "Nimra Institute of Medical Sciences, Krishna Dist., A.P.",
    "P E S Institute Of Medical Sciences and Research, Kuppam",
    "Rajiv Gandhi Institute of Medical Sciences, Kadapa",
    "Rajiv Gandhi Institute of Medical Sciences, Srikakulam",
    "Rajiv Gandhi Institute of Medical Sciences,Ongole, AP",
    "Rangaraya Medical College, Kakinada",
    "S V Medical College, Tirupati",
    "SVIMS - Sri Padmavathi Medical College for Women, Alipiri Road, Tirupati",
    "Santhiram Medical College, Nandyal",
    "Viswabharathi Medical College, Kurnool",
  ],
  "Arunachal Pradesh": [
    "Tomo Riba Institute of Health & Medical Sciences, Naharlagun",
  ],
  "Assam": [
    "All India Institute of Medical Sciences, Guwahati",
    "Assam Medial College, Dibrugarh",
    "Dhubri Medical College, Dhubri",
    "Diphu Medical College & Hospital, Diphu, Assam",
    "Fakhruddin Ali Ahmed Medical College, Barpeta, Assam",
    "Gauhati Medical College, Guwahati",
    "Jorhat Medical College & Hospital , Jorhat",
    "Kokrajhar Medical College and Hospital",
    "Lakhimpur Medical College, Lakhimpur, Assam",
    "Nagaon Medical College",
    "Nalbari Medical College and Hospital",
    "Nalbari Medical College, Nalbari",
    "Silchar Medical College, Silchar",
    "Tezpur Medical College & Hospital, Tezpur",
  ],
  "Bihar": [
    "All India Institute of Medical Sciences, Patna",
    "Anugrah Narayan Magadh Medical College, Gaya",
    "Darbhanga Medical College, Lehriasarai",
    "Employees State Insurance Corporation Medical College, Patna",
    "Government Medical College, Bettiah",
    "Government Medical College, Purnea",
    "Indira Gandhi Institute of Medical Sciences,Sheikhpura, Patna",
    "Jannayak Karpoori Thakur Medical College & Hospital, Madhepura, Bihar",
    "Jawaharlal Nehru Medical College, Bhagalpur",
    "Katihar Medical College, Katihar",
    "Lord Buddha Koshi Medical College and Hospital, Saharsa",
    "Madhubani Medical College, Madhubani",
    "Mata Gujri Memorial Medical College, Kishanganj",
    "Nalanda Medical College, Patna",
    "Narayan Medical College & Hospital, Sasaram",
    "Netaji Subhas Medical College & Hospital, Amhara, Bihta, Patna",
    "Patna Medical College, Patna",
    "Radha Devi Jageshwari Memorial Medical College and Hospital",
    "Shree Narayan Medical Institute and Hospital",
    "Shri Krishna Medical College, Muzzafarpur",
    "Vardhman Institute of Medical Sciences, Pawapuri, Nalanda",
  ],
  "Chandigarh": ["Government Medical College, Chandigarh"],
  "Chattisgarh": [
    "All India Institute of Medical Sciences, Raipur",
    "Chandulal Chandrakar Memorial Medical College, Durg",
    "Chhattisgarh Institute of Medical Sciences, Bilaspur",
    "Government Medical College (Bharat Ratna Shri Atal Bihari Vajpyee Memorial Med. Col.), Rajnandgaon",
    "Government Medical College, Ambikapur (Surguja), Chhattisgarh",
    "Government Medical College, Kanker",
    "Government Medical College, Korba",
    "Government Medical College, Mahasamund",
    "Late Shri Baliram Kashyap Memorial NDMC Govt. Medical College, Jagdalpur",
    "Late Shri Lakhi Ram Agrawal Memorial Govt. Medical College, Raigarh",
    "Pt. J N M Medical College, Raipur",
    "Raipur Institute of Medical Sciences (RIMS), Raipur",
    "Shri Balaji Institute of Medical Science",
    "Shri Shankaracharya Institute of Medical Sciences, Bhilai",
  ],
  "Dadra and Nagar Haveli": [
    "Shri Vinoba Bhave Institute of Medical Sciences, (Govt. Medical College) Silvassa, U.T",
  ],
  "Delhi": [
    "All India Institute of Medical Sciences, New Delhi",
    "Army College of Medical Sciences, New Delhi",
    "Dr. Baba Saheb Ambedkar Medical College, Rohini, Delhi",
    "Hamdard Institute of Medical Sciences & Research, New Delhi",
    "Lady Hardinge Medical College, New Delhi",
    "Maulana Azad Medical College, New Delhi",
    "North Delhi Muncipal Corporation Medical College, Delhi",
    "PGIMER Dr. RML Hospital, New Delhi",
    "University College of Medical Sciences & GTB Hospital, New Delhi",
    "Vardhman Mahavir Medical College & Safdarjung Hospital, Delhi",
  ],
  "Goa": ["Goa Medical College, Panaji"],
  "Gujarat": [
    "Ahmedabad Municipal Coporation Medical Education Trust Medical College, Ahmedabad",
    "All India Institute of Medical Sciences, Rajkot",
    "Ananya College of Medicine & Research",
    "B J Medical College, Ahmedabad",
    "Banas Medical College and Research Institute, Palanpur, Gujarat",
    "CU Shah Medical College, Surendra Nagar",
    "Dr. M.K. Shah Medical College & Research Centre, Ahmedabad",
    "Dr. N.D. Desai Faculty of Medical Science and Research, Nadiad",
    "Dr.Kiran C.Patel Medical College and Research Institute",
    "GCS Medical College, Ahmedabad",
    "GMERS Medical College, Dharpur Patan",
    "GMERS Medical College, Gandhinagar",
    "GMERS Medical College, Gotri, Vadodara",
    "GMERS Medical College, Hadiyol, Himmatnagar",
    "GMERS Medical College, Junagadh",
    "GMERS Medical College, Navsari",
    "GMERS Medical College, Rajpipla",
    "GMERS Medical College, Sola, Ahmedabad",
    "GMERS Medical College, Vadnagar, Mehsana",
    "GMERS Medical College, Valsad",
    "Government Medical College, Bhavnagar",
    "Government Medical College, Morbi",
    "Government Medical College, Panchmahal Godhra",
    "Government Medical College, Porbandar",
    "Government Medical College, Surat",
    "Gujarat Adani Institute of Medical Sciences, Bhuj",
    "MP Shah Medical College,Jamnagar",
    "Medical College, Baroda",
    "Nootan Medical College and Research Centre, Mehsana",
    "Pandit Deendayal Upadhyay Medical College, Rajkot",
    "Parul Institute of Medical Sciences & Research, Vadodara",
    "Pramukhswami Medical College, Karmsad",
    "SAL Institute of Medical Sciences, Ahmedabad",
    "SBKS Medical Institute & Research Centre, Vadodara",
    "Shantabaa Medical College & General Hospital, Amreli",
    "Smt. N.H.L.Municipal Medical College, Ahmedabad",
    "Surat Municipal Institute of Medical Education & Research, Surat",
    "Swaminayaran Institute of Medical Sciences & Research",
    "Zydus Medical College & Hospital, Dahod",
  ],
  "Haryana": [
    "Adesh Medical College and Hospital, Shahabad, Kurukshetra, Haryana",
    "Al Falah School of Medical Sciences & Research Centre, Faridabad",
    "Amrita School of Medicine, Faridabad",
    "BPS Government Medical College for Women, Sonepat",
    "Employees State Insurance Corporation Medical College, Faridabad",
    "Faculty of Medicine and Health Sciences, Gurgaon (Formarly SGGST Medical College & R Centre,Gurgaon)",
    "Kalpana Chawala Govt. Medical College, Karnal, Haryana",
    "Maharaja Agrasen Medical College, Agroha",
    "Maharishi Markandeshwar College of Medical Sciences & Research, Sadopur",
    "Maharishi Markandeshwar Institute Of Medical Sciences & Research, Mullana, Ambala",
    "N.C. Medical College & Hospital, Panipat",
    "Pt. B D Sharma Postgraduate Institute of Medical Sciences, Rohtak (Haryana)",
    "Shaheed Hasan Khan Mewati Government Medical College, Nalhar",
    "Shri Atal Bihari Vajpayee Government Medical College, Faridabad",
    "World College of Medical Sciences & Researc, Jhajjar, Haryana",
  ],
  "Himachal Pradesh": [
    "All India Institute of Medical Sciences, Bilaspur",
    "Dr. Radhakrishnan Government Medical College, Hamirpur, H.P",
    "Dr. Rajendar Prasad Government Medical College, Tanda, H.P",
    "Government Medical College, Nahan, Sirmour H.P.",
    "Indira Gandhi Medical College, Shimla",
    "Maharishi Markandeshwar Medical College & Hospital, Solan",
    "Pt. Jawahar Lal Nehru Government Medical College, Chamba",
    "Shri Lal Bahadur Shastri Government Medical College, Mandi, HP",
  ],
  "Jammu and Kashmir": [
    "Acharya Shri Chander College of Medical Sciences, Jammu",
    "All India Institute of Medical Sciences, Vijaypur",
    "Government Medical College & Associated Hospital, Rajouri, J&K",
    "Government Medical College, Anantnag",
    "Government Medical College, Baramulla",
    "Government Medical College, Handwara",
    "Government Medical College, Jammu",
    "Government Medical College, Kathua",
    "Government Medical College, Srinagar",
    "Government Medical College, Udhampur",
    "Govt. Medical College, Doda, Kashmir",
    "Sher-I-Kashmir Instt. Of Medical Sciences, Srinagar",
  ],
  "Jharkhand": [
    "All India Institute of Medical Sciences, Deoghar",
    "Dumka Medical College, Dighi Dumka",
    "Hazaribagh Medical College, Hazaribagh",
    "Laxmi Chandravansi Medical College & Hospital",
    "M G M Medical College, Jamshedpur",
    "Manipal Tata Medical College,Baridih Jameshedpur",
    "Palamu Medical College, Palamu",
    "Patliputra Medical College, Dhanbad",
    "Rajendra Institute of Medical Sciences, Ranchi",
  ],
  "Karnataka": [
    "A J Institute of Medical Sciences & Research Centre, Mangalore",
    "Adichunchanagiri Institute of Medical Sciences Bellur",
    "Akash Institute of Medical Sciences & Research Centre, Devanhalli, Bangalore, Karnataka",
    "Al-Ameen Medical College,Bijapur",
    "BGS Global Institute of Medical Sciences, Bangalore",
    "Bangalore Medical College and Research Institute, Bangalore",
    "Basaveswara Medical College and Hospital, Chitradurga",
    "Belagavi Institute of Medical Sciences, Belagavi/Belgaum",
    "Bidar Institute of Medical Sciences,Bidar",
    "Chamrajanagar Institute of Medical Sciences, Karnataka",
    "Chikkaballapura Institute of Medical Sciences",
    "Chikkamagaluru Institute of Medical Sciences, Chikkamagaluru",
    "Chitradurga Medical College and Research Institute",
    "Dr BR Ambedkar Medical College, Bangalore",
    "Dr. Chandramma Dayananda Sagar Instt. of Medical Education & Research, Harohalli, Hubli",
    "East Point College of Medical Sciences & Research Centre, Bangalore",
    "Employees State Insurance Corporation Medical College, Bangalore",
    "Employees State Insurance Corporation Medical College, Gulbarga",
    "Father Mullers Medical College, Mangalore",
    "G R Medical College Hospital & Research Centre",
    "Gadag Institute of Medical Sciences, Mallasamudra, Mulgund Road, Gadag",
    "Gulbarga Institute of Medical Sciences, Gulbarga",
    "Hassan Institute of Medical Sciences, Hassan",
    "Haveri Institute of Medical Sciences, Haveri",
    "JJM Medical College, Davangere",
    "JSS Medical College, Mysore",
    "Jagadguru Gangadhar Mahaswamigalu Moorusavirmath Medical College JGMMMC",
    "Jawaharlal Nehru Medical College, Belgaum",
    "K S Hegde Medical Academy, Mangalore",
    "K V G Medical College, Sullia",
    "Kanachur Institute of Medical Sciences, Mangalore",
    "Karnataka Institute of Medical Sciences, Hubli/Hubballi",
    "Karwar Institute of Medical Sciences, Karwar",
    "Kasturba Medical College, Mangalore",
    "Kasturba Medical College, Manipal",
    "Kempegowda Institute of Medical Sciences, Bangalore",
    "Khaja Bandanawaz University - Faculty of Medical Sciences, Gulbarga",
    "Kodagu Institute of Medical Sciences, Kodagu",
    "Koppal Institute of Medical Sciences, Koppal",
    "M S Ramaiah Medical College, Bangalore",
    "MVJ Medical College and Research Hospital, Bangalore",
    "Mahadevappa Rampure Medical College, Kalaburagi, Gulbarga",
    "Mandya Institute of Medical Sciences, Mandya",
    "Mysore Medical College and Research Instt. (Prev.name Government Medical College), Mysore",
    "National Institute of Mental Health and Neuro Sciences NIMHANS, Bangalore",
    "Navodaya Medical College, Raichur",
    "Raichur Institute of Medical Sciences,Raichur",
    "Rajarajeswari Medical College & Hospital, Bangalore",
    "S S Institute of Medical Sciences& Research Centre, Davangere",
    "S. Nijalingappa Medical College & HSK Hospital & Research Centre, Bagalkot",
    "SDM College of Medical Sciences & Hospital, Sattur, Dharwad",
    "Sambharam Institute of Medical Sciences & Research, Kolar",
    "Sapthagiri Institute of Medical Sciences & Research Centre, Bangalore",
    "Shimoga Institute of Medical Sciences,Shimoga",
    "Shri Atal Bihari Vajpayee Medical College & Research Institute",
    "Shri B M Patil Medical College, Hospital & Research Centre, Vijayapura(Bijapur)",
    "Shridevi Institute of Medical Sciences & Research Hospital, Tumkur",
    "Siddaganga Medical College and Research Institute, Tumakuru",
    "Sri Chamundeshwari Medical College Hospital & Research Institute",
    "Sri Devaraj URS Medical College, Kolar",
    "Sri Madhusudan Sai Institute of Medical Sciences and Research",
    "Sri Siddhartha Medical College, Tumkur",
    "Sri siddhartha Institute of Medical Sciences & Research Centre, Bangalore",
    "Srinivas Institute of Medical Research Centre, Srinivasnagar",
    "St. Johns Medical College, Bangalore",
    "Subbaiah Institute of Medical Sciences, Shimoga, Karnataka",
    "The Oxford Medical College, Hospital & Research Centre, Bangalore",
    "Vijaynagar Institute of Medical Sciences, Bellary",
    "Vydehi Institute Of Medical Sciences & Research Centre, Bangalore",
    "Yadgiri Institute of Medical Sciences, Yadgiri",
    "Yenepoya Medical College, Mangalore",
  ],
  "Kerala": [
    "Al-Azhar Medical College and Super Speciality Hospital, Thodupuzha",
    "Amala Institute of Medical Sciences, Thrissur",
    "Amrita School of Medicine, Elamkara, Kochi",
    "Azeezia Instt of Medical Science,Meeyannoor,Kollam",
    "Believers Church Medical College Hospital, Thiruvalla, Kerala",
    "DM Wayanad Institute of Medical Sciences, Wayanad, Kerala",
    "Dr. Somervel Memorial CSI Hospital & Medical College, Karakonam, Thiruvananthapuram",
    "Government Medical College (Institute of Integrated Medical Sciences), Yakkara, Palakkad",
    "Government Medical College, Ernakulam",
    "Government Medical College, Konni",
    "Government Medical College, Kottayam",
    "Government Medical College, Kozhikode, Calicut",
    "Government Medical College, Manjeri, Malapuram Dist.",
    "Government Medical College, Painav, Idukki",
    "Government Medical College, Parippally, Kollam",
    "Government Medical College, Thrissur",
    "Govt. Medical College,Pariyaram, Kannur (Prev. Known as Academy of Medical Sciences)",
    "Jubilee Mission Medical College & Research Institute, Thrissur",
    "KMCT Medical College,Kozhikode, Calicut",
    "Kannur Medical College, Kannur",
    "Karuna Medical College, Palakkad",
    "M E S Medical College , Perintalmanna Malappuram Distt.Kerala",
    "Malabar Medical College, Kozhikode,Calicut",
    "Malankara Orthodox Syrian Church Medical College, Kolenchery",
    "Medical College, Thiruvananthapuram",
    "Mount Zion Medical College, Chayalode, Ezhamkulam Adoor, Pathanamthitta",
    "P K Das Institute of Medical Sciences, Palakkad, Kerala",
    "Pushpagiri Institute Of Medical Sciences and Research Centre, Tiruvalla",
    "Sree Gokulam Medical College Trust & Research Foundation, Trivandrum",
    "Sree Narayana Instt. of Medical Sciences, Chalakka,Ernakulam",
    "Sree Uthradom Thiurnal Academy of Medical Sciences,Trivandrum",
    "T D Medical College, Alleppey (Allappuzha)",
    "Travancore Medical College, Kollam",
  ],
  "Madhya Pradesh": [
    "All India Institute of Medical Sciences, Bhopal",
    "Amaltas Institute of Medical Sciences, Dewas",
    "Bundelkhand Medical College, Sagar",
    "Chirayu Medical College and Hospital, Bairagarh,Bhopal",
    "Gajra Raja Medical College, Gwalior",
    "Gandhi Medical College, Bhopal",
    "Government Medical College, Chhindwara, MP",
    "Government Medical College, Datia, MP",
    "Government Medical College, Khandwa, MP",
    "Government Medical College, Ratlam",
    "Government Medical College, Satna",
    "Government Medical College, Shahdol, MP",
    "Government Medical College, Shivpuri, MP",
    "Government Medical College, Vidisha, MP",
    "Index Medical College Hospital & Research Centre,Indore",
    "L.N. Medical College and Research Centre,Bhopal",
    "LNCT Medical College & Sewakunj Hospital, Indore",
    "M G M Medical College, Indore",
    "Mahaveer Institute of Medical Sciences & Research, Bhopal",
    "Netaji Subhash Chandra Bose Medical College, Jabalpur",
    "Peoples College of Medical Sciences & Research Centre, Bhanpur, Bhopal",
    "RKDF Medical College Hospital & Research Centre, Jatkhedi, Bhopal",
    "Ruxmaniben Deepchand Gardi Medical College, Ujjain",
    "Shyam Shah Medical College, Rewa",
    "Sri Aurobindo Medical College and Post Graduate Institute , Indore",
    "Sukh Sagar Medical College & Hospital, Jabalpur",
  ],
  "Maharashtra": [
    "ACPM Medical College, Dhule",
    "All India Institute of Medical Sciences, Nagpur",
    "Armed Forces Medical College, Pune",
    "Ashwini Rural Medical College, Hospital & Research Centre, Solapur",
    "B. J. Govt. Medical College, Pune",
    "B.K.L. Walawalkar Rural Medical College, Ratnagiri",
    "Bharati Vidyapeeth Deemed University Medical College & Hospital, Sangli",
    "Bharati Vidyapeeth University Medical College, Pune",
    "Bharatratna Atal Bihari Vajpayee Medical College, Pune",
    "Datta Meghe Medical College, Nagpur",
    "Dr Vaishampayan Memorial Medical College, Solapur",
    "Dr. D Y Patil Medical College, Hospital and Research Centre, Pimpri, Pune",
    "Dr. D Y Patil Medical College, Kolhapur",
    "Dr. N Y Tasgaonkar Institute of Medical Science",
    "Dr. Panjabrao Alias Bhausaheb Deshmukh Memorial Medical College, Amravati",
    "Dr. Rajdendra Gode Medical College, Amravati",
    "Dr. Shankarrao Chavan Govt. Medical College, Nanded",
    "Dr. Ulhas Patil Medical College & Hospital, Jalgaon",
    "Dr.Vasantrao Pawar Med. Col. Hosp. & Research Centre,Nasik (Prev. NDMVP Samaj Medical College)",
    "Government Medical College & Hospital, Baramati",
    "Government Medical College, Akola",
    "Government Medical College, Alibag",
    "Government Medical College, Aurangabad",
    "Government Medical College, Chandrapur",
    "Government Medical College, Gondia",
    "Government Medical College, Jalgaon",
    "Government Medical College, Latur",
    "Government Medical College, Miraj",
    "Government Medical College, Nagpur",
    "Government Medical College, Nandurbar",
    "Government Medical College, Osmanabad",
    "Government Medical College, Satara",
    "Government Medical College, Sindhudurg",
    "Government Medical college and District Hospital, Ratnagiri",
    "Grant Medical College, Mumbai",
    "H.B.T. Medical College & Dr. R.N. Cooper Municipal General Hospital, Juhu, Mumbai",
    "Indian Institute of Medical Science & Research, Jalna",
    "Indira Gandhi Medical College & Hospital, Nagpur",
    "Jawaharlal Nehru Medical College, Sawangi (Meghe), Wardha",
    "KJ Somaiyya Medical College & Research Centre, Mumbai",
    "Krishna Institute of Medical Sciences, Karad",
    "Lokmanya Tilak Municipal Medical College, Sion, Mumbai",
    "Maharashtra Institute of Medical Education & Research, Talegaon,Pune",
    "Maharashtra Institute of Medical Sciences & Research, Latur",
    "Mahatma Gandhi Institute of Medical Sciences, Sevagram, Wardha",
    "Mahatma Gandhi Mission Medical College, Vashi",
    "Mahatma Gandhi Missions Medical College, Aurangabad",
    "Mahatma Gandhi Missions Medical College, Navi Mumbai",
    "N. K. P. Salve Instt. of Medical Sciences and Research Centre and Lata Mangeshkar Hospital, Nagpur",
    "Padmashree Dr. D.Y.Patil Medical College, Navi Mumbai",
    "Padmashri Dr. Vithalrao Vikhe Patil Foundations Medical College & Hospital, Ahmednagar",
    "Parbhani Medical College, Parbhani",
    "Prakash Institute of Medical Sciences & Research, Sangli",
    "Rajashree Chatrapati Shahu Maharaj Government Medical College, Kolhapur",
    "Rajiv Gandhi Medical College and Chhatrapati Shivaji Maharaj Hospital, Thane",
    "Rural Medical College, Loni",
    "SMBT Institute of Medical Sciences & Research Centre, Nandihills, Nashik",
    "SRTR Medical College, Ambajogai",
    "Seth GS Medical College, Mumbai",
    "Shri Vasant Rao Naik Govt. Medical College, Yavatmal",
    "Sindhudurg Shikshan Prasarak Mandal (SSPM) Medical College & Lifetime Hospital, Padave, Sindhudurg",
    "Smt. Kashibai Navale Medical College and General Hospital,Pune",
    "Sri Bhausaheb Hire Government Medical College, Dhule",
    "Symbiosis Medical College for Women, Pune",
    "Terna Medical College, Navi Mumbai",
    "Topiwala National Medical College, Mumbai",
    "Vedantaa Institute of Medical Sciences, Palghar, Maharashtra",
  ],
  "Manipur": [
    "Government Medical College, Churachandpur",
    "Jawaharlal Nehru Institute of Medical Sciences,Porompet,Imphal",
    "Regional Institute of Medical Sciences, Imphal",
    "Shija Academy of Health Sciences, Imphal, Manipur",
  ],
  "Meghalaya": [
    "North Eastern Indira Gandhi Regional Instt. of Health and Medical Sciences, Shillong",
  ],
  "Mizoram": ["Zoram Medical College, Mizoram"],
  "Nagaland": ["Nagaland Institute of Medical Sciences & Research"],
  "Odisha": [
    "All India Institute of Medical Sciences, Bhubaneswar",
    "DRIEMS Institute of Health Sciences and Hospital, Kairapari",
    "Government Medical College & Hospital (Renamed as Bhima Bhoi Medical College & Hospital), Balangir",
    "Government Medical College & Hospital (Renamed as Fakir Mohan Medical College & Hospital), Balasore",
    "Government Medical College and Hospital, Bhawanipatna",
    "Government Medical College, Keonjhar",
    "Government Medical College, Sundargarh",
    "Hi-Tech Medical College & Hospital, Bhubaneswar",
    "Hi-Tech Medical College & Hospital, Rourkela",
    "Instt. Of Medical Sciences & SUM Hospital, Bhubaneswar",
    "Kalinga Institute of Medical Sciences, Bhubaneswar",
    "MKCG Medical College, Berhampur",
    "Pt. Raghunath Murmu Medical College and Hospital, Baripada, Odisha",
    "SCB Medical College, Cuttack",
    "Saheed Laxman Nayak Medical College & Hospital, Koraput",
    "Sardar Rajas Medical College, Hospital and Research Centre, Jaring, Kalahandi",
    "Sri Jagannath Medical College & Hospital, Puri",
    "Veer Surendra Sai Institute of Medical Sciences and Research, Burla",
  ],
  "Pondicherry": [
    "Aarupadai Veedu Medical College, Pondicherry",
    "Indira Gandhi Medical College & Research Institute, Puducherry",
    "Jawaharlal Institute of Postgraduate Medical Education & Research, Puducherry",
    "Mahatma Gandhi Medical College & Research Institute, Pondicherry",
    "Pondicherry Institute of Medical Sciences & Research, Pondicherry",
    "Sri Lakshmi Narayana Institute of Medical Sciences, Pondicherry",
    "Sri Manakula Vinayagar Medical College & Hospital, Pondicherry",
    "Sri Venkateswaraa Medical College, Hospital & Research Centre, Pondicherry",
    "Vinayaka Missions Medical College, Karaikal, Pondicherry",
  ],
  "Punjab": [
    "Adesh Institute of Medical Sciences & Research, Bhatinda",
    "All India Institute of Medical Sciences, Bhatinda",
    "Chintpurni Medical College, Gurdaspur",
    "Christian Medical College, Ludhiana",
    "Dayanand Medical College & Hospital, Ludhiana",
    "Dr. B R Ambedkar State Institute of Medical Sciences, SAS Nagar, Mohali",
    "Gian Sagar Medical College & Hospital, Patiala",
    "Government Medical College, Amritsar",
    "Government Medical College, Patiala",
    "Guru Govind Singh Medical College, Faridkot",
    "Punjab Institute of Medical Sciences, Jalandhar",
    "Sri Guru Ram Das Institute of Medical Sciences and Research, Sri Amritsar",
  ],
  "Rajasthan": [
    "All India Institute of Medical Sciences, Jodhpur",
    "American International Institute of Medical Sciences, Bedwas",
    "Ananta Institute of Medical Sciences & Research Centre, Rajsamand",
    "Dr SN Medical College, Jodhpur",
    "Dr. S S Tantia Medical College Hospital & Research Centre",
    "Employees State Insurance Corporation Medical College, Alwar",
    "Geetanjali Medical College & Hospital,Udaipur",
    "Government Medical College, Alwar",
    "Government Medical College, Barmer",
    "Government Medical College, Bharatpur, Rajasthan",
    "Government Medical College, Bhilwara, Rajasthan",
    "Government Medical College, Bundi",
    "Government Medical College, Chittorgarh",
    "Government Medical College, Churu",
    "Government Medical College, Dausa",
    "Government Medical College, Dholpur",
    "Government Medical College, Dungarpur",
    "Government Medical College, Hanumangarh",
    "Government Medical College, Karauli",
    "Government Medical College, Kota",
    "Government Medical College, Pali, Rajasthan",
    "Government Medical College, Sirohi",
    "Government Medical College, Sri Ganganagar",
    "Jaipur National University Institute of Medical Sciences and Resarch Centre, Jagatpura, Jaipur",
    "Jawaharlal Nehru Medical College, Ajmer",
    "Jhalawar Medical College, Jhalawar",
    "Mahatma Gandhi Medical College and Hospital, Sitapur, Jaipur",
    "National Institute of Medical Science & Research, Jaipur",
    "Pacific Institute of Medical Sciences, Umarda, Udaipur",
    "Pacific Medical College & Hospital, Bhilo Ka Bedla, Udaipur",
    "R N T Medical College, Udaipur",
    "RUHS College of Medical Sciences, Jaipur",
    "SMS Medical College, Jaipur",
    "Sardar Patel Medical College, Bikaner",
    "Shri Kalyan Govt. Medical College, Sikar, Rajasthan",
  ],
  "Sikkim": ["Sikkim Manipal Institute of Medical Sciences, Gangtok"],
  "Tamil Nadu": [
    "ACS Medical College and Hospital, Chennai",
    "All India Institute of Medical Sciences, Madurai",
    "Annapoorna Medical College & Hospital, Salem",
    "Arunai Medical College And Hospital",
    "Bhaarat Medical College & Hospital",
    "Chengalpattu Medical College, Chengalpattu",
    "Chettinad Hospital & Research Institute, Kanchipuram",
    "Christian Medical College, Vellore",
    "Coimbatore Medical College, Coimbatore",
    "Dhanalakshmi Srinivasan Institute of Medical Sciences and Hospital,",
    "Dhanalakshmi Srinivasan Medical College and Hospital,Perambalur",
    "ESI-PGIMSR,ESI Hospital,K.K Nagar,Chennai",
    "Faculty of Medicine, Sri Lalithambigai Medical College and Hospital",
    "Government Ariyalur medical College, Tamilnadu",
    "Government Dharmapuri Medical College, Dharmapuri",
    "Government Erode Medical College & Hospital, Perundurai (Formerly IRT Perundurai Medical College)",
    "Government Medical College & ESIC Hospital, Coimbatore, TamilNadu",
    "Government Medical College Kallakurichi",
    "Government Medical College Nagapattinam",
    "Government Medical College Ramanathapuram",
    "Government Medical College and Hospital, Krishnagiri",
    "Government Medical College, Dindigul",
    "Government Medical College, Karur",
    "Government Medical College, Namakkal",
    "Government Medical College, Omandurar",
    "Government Medical College, Pudukottai, Tamil Nadu",
    "Government Medical College, The Nilgiris",
    "Government Medical College, Thiruvallur",
    "Government Medical College, Tiruppur",
    "Government Medical College, Virudhunagar",
    "Government Sivagangai Medical College, Sivaganga",
    "Government Thiruvannamalai Medical College, Thiruvannamalai",
    "Government Vellore Medical College, Vellore",
    "Government Villupuram Medical College, Villupuram",
    "Indira Medical College & Hospitals, Thiruvallur",
    "K A P Viswanathan Government Medical College, Trichy",
    "KMCH Institute of Health sciences and Research, Coimbatore",
    "KanyaKumari Government Medical College, Asaripallam",
    "Karpaga Vinayaga Institute of Medical Sciences,Maduranthagam",
    "Karpagam Faculty of Medical Sciences & Research, Coimbatore",
    "Kilpauk Medical College, Chennai",
    "Madha Medical College and Hospital, Thandalam, Chennai",
    "Madras Medical College, Chennai",
    "Madurai Medical College, Madurai",
    "Meenakshi Medical College and Research Institute, Enathur",
    "Melmaruvathur Adiparasakthi Instt. Medical Sciences and Research",
    "Mohan Kumaramangalam Medical College, Salem",
    "Nandha Medical College & Hospital Erode",
    "PSG Institute of Medical Sciences, Coimbatore",
    "PSP Medical College Hospital and Research Institute",
    "Panimalar Medical College Hospital & Research Institute, Chennai,Tamil Nadu",
    "Rajah Muthiah Medical College, Annamalainagar",
    "SRM Medical College Hospital & Research Centre, Kancheepuram",
    "ST Peters Medical College, Hospital & Research Institute",
    "Saveetha Medical College and Hospital, Kanchipuram",
    "Shri Satya Sai Medical College and Research Institute, Kancheepuram",
    "Sree Balaji Medical College and Hospital, Chennai",
    "Sree Mookambika Institute of Medical Sciences, Kanyakumari",
    "Sri Muthukumaran Medical College,Chennai",
    "Sri Ramachandra Medical College & Research Institute, Chennai",
    "Sri Venkateswaraa Medical College Hospital and Research Institute, Nallur, Redhills",
    "Srinivasan Medical College and Hospital",
    "Stanley Medical College, Chennai",
    "Tagore Medical College and Hospital, Chennai",
    "Thanjavur Medical College,Thanjavur",
    "Theni Government Medical College,Theni",
    "Thiruvarur Govt. Medical College, Thiruvarur",
    "Thoothukudi Medical College, Thoothukudi",
    "Tirunelveli Medical College,Tirunelveli",
    "Trichy SRM Medical College Hospital & Research Centre, Trichy",
    "VELS Medical College & Hospital",
    "Velammal Medical College Hospital and Research Institute, Madurai",
    "Vinayaka Missions Kirupananda Variyar Medical College, Salem",
  ],
  "Telangana": [
    "All India Institute of Medical Sciences, Bibinagar",
    "Apollo Institute of Medical Sciences and Research, Hyderabad",
    "Arundathi Institute of Medical Sciences",
    "Ayaan Institute of medical sciences, Teaching Hospital & Research Centre, Kanaka Mamidi, R. R. dist",
    "Bhaskar Medical College, Yenkapally",
    "CMR Institute of Medical Sciences",
    "Chalmeda Anand Rao Insttitute Of Medical Sciences, Karimnagar",
    "Deccan College of Medical Sciences, Hyderabad",
    "Dr. Patnam Mahender Reddy Institute of Medical Sciences, Chevella, Rangareddy",
    "Dr. VRK Womens Medical College, Aziznagar",
    "Employees State Insurance Coporation Medical College, Sanath Nagar, Hyderabad",
    "Gandhi Medical College, Secunderabad",
    "Government Medical College Jangaon",
    "Government Medical College, Bhadradri Kothagudem",
    "Government Medical College, Jagtial",
    "Government Medical College, Jayashankar Bhupalpally",
    "Government Medical College, Kamareddy",
    "Government Medical College, Karimnagar",
    "Government Medical College, Khammam",
    "Government Medical College, Kumuram Bheem Asifabad",
    "Government Medical College, Mahabubabad",
    "Government Medical College, Mahabubnagar",
    "Government Medical College, Mancherial",
    "Government Medical College, Nagarkurnool",
    "Government Medical College, Nalgonda",
    "Government Medical College, Nirmal",
    "Government Medical College, Nizamabad",
    "Government Medical College, Rajanna Sircilla",
    "Government Medical College, Ramagundam",
    "Government Medical College, Sangareddy",
    "Government Medical College, Siddipet",
    "Government Medical College, Suryapet",
    "Government Medical College, Vikarabad",
    "Government Medical College, Wanaparthy",
    "Kakatiya Medical College, Wrangal",
    "Kamineni Academy of Medical Sciences & Research Center, Hyderabad",
    "Kamineni Institute of Medical Sciences, Narketpally",
    "MNR Medical College & Hospital, Sangareddy",
    "Mahavir Institute of Medical sciences, Vikarabad, Telangana",
    "Maheshwara Medical College, Chitkul, Patancheru, Medak",
    "Malla Reddy Institute of Medical Sciences, Hyderabad",
    "Mallareddy Medical College for Womens, Hyderabad",
    "Mamata Academy of Medical Sciences, Bachupally",
    "Mamata Medical College, Khammam",
    "Mediciti Institute Of Medical Sciences, Ghanpur",
    "Neelima Institute of Medical Sciences, Medchal",
    "Osmania Medical College, Hyderabad",
    "Prathima Institute Of Medical Sciences, Karimnagar",
    "R.V.M. Institute of Medical Sciences and Research Centre, Siddipet",
    "Rajiv Gandhi Institute of Medical Sciences, adilabad",
    "S V S Medical College, Mehboobnagar",
    "Shadan Institute of Medical Sciences,Research Centre and Teaching Hospital, Peerancheru",
    "Surabhi Institute of Medical Sciences, Siddipet, Telangana",
    "TRR Institute of Medical Sciences, patancheru",
  ],
  "Tripura": [
    "Agartala Government Medical College,Agartala",
    "Tripura Medical College and Dr. B R A M Teaching Hospital, Agartala",
  ],
  "Uttar Pradesh": [
    "All India Institute of Medical Sciences, Gorakhpur",
    "All India Institute of Medical Sciences, Rae Bareli",
    "Autonomous State Medical College Pratapgarh",
    "Autonomous State Medical College Society Ghazipur",
    "Autonomous State Medical College Society, Etah, Uttar Pradesh",
    "Autonomous State Medical College Society, Fatehpur",
    "Autonomous State Medical College Society, Hardoi",
    "Autonomous State Medical College, Siddharthnagar",
    "Autonomous State Society Medical College Mirzapur",
    "BRD Medical College, Gorakhpur",
    "Career Instt. Of Medical Sciences & Hospital, Lucknow",
    "Dr. Ram Manohar Lohia Institute of Medical Sciences,Lucknow",
    "Era Lucknow Medical College , Lucknow",
    "F.H. Medical College & Hospital, Etamdapur, Agra",
    "G.S. Medical College & Hospital, Hapur, UP",
    "GSVM Medical College, Kanpur",
    "Government Allopathic Medical College, Banda, UP",
    "Government Institute of Medical Sciences, Kasna, Greater Noida",
    "Government Medical College & Super facility Hospital, Azamgarh",
    "Government Medical College, Badaun",
    "Government Medical College, Faizabad(Rajarshi Dashrath Autonomous State Medical College,Ayodhya)",
    "Government Medical College, Firozabad",
    "Government Medical College, Kannauj",
    "Government Medical College, Rampur, Basti",
    "Government Medical College, Shahjahanpur, UP",
    "Heritage Institute of Medical Sciences, Varanasi",
    "Hind Institute of Medical Sciences , Barabanki",
    "Hind Institute of Medical Sciences, Sitapur",
    "Institute of Medical Sciences, BHU, Varansi",
    "Integral Institute of Medical Sciences & Research, Lucknow",
    "Jawaharlal Nehru Medical College, Aligarh",
    "K.D. Medical College Hospital & Research Centre, Mathura",
    "King George Medical University, Lucknow",
    "Krishna Mohan Medical College & Hospital, Mathura",
    "LLRM Medical College, Meerut",
    "Mahamaya Rajkiya Allopathic Medical College, Ambedkarnagar",
    "Maharaja Suheldev Autonomous State Medical College and Maharishi Balark Hospital",
    "Maharani Laxmi Bai Medical College, Jhansi",
    "Maharshi Devraha Baba Autonomous State Medical College, Deoria",
    "Manyavar Kanshi Ram Ji Government Allopathic Medical College, Orai, Jalaun",
    "Mayo Institute of Medical Sciences, Barabanki",
    "Moti Lal Nehru Medical College, Allahabad",
    "Muzaffarnagar Medical College, Muzaffarnagar",
    "Naraina Medical College & Research Centre, Kanpur",
    "National Capital Region Institute of Medical Sciences, Meerut",
    "Noida International Institute Of Medical Sciences",
    "Prasad Institute of Medical Sciences, Lucknow",
    "Rajshree Medical Research Institute, Bareilly",
    "Rama Medical College Hospital and Research Centre, Hapur",
    "Rama Medical College and Hospital , Kanpur",
    "Rohilkhand Medical College & Hospital, Bareilly",
    "S N Medical College, Agra",
    "SKS Hospital Medical College & Research Centre",
    "Santosh Medical College, Ghaziabad",
    "Saraswati Institute of Medical Sciences, Hapur",
    "Saraswati Medical College, Unnao, U.P.",
    "School of Medical Sciences & Research,Greater Noida",
    "Shaikh-UL-Hind Maulana Mahmood Hasan Medical College, Saharanpur",
    "Shri Ram Murti Smarak Institute of Medical Sciences, Bareilly",
    "Subharti Medical College, Meerut",
    "T S Misra Medical College & Hospital, Amusi, Lucknow",
    "Teerthanker Mahaveer Medical College, Moradabad",
    "Uma Nath Singh Autonomous State Medical College Society Jaunpur",
    "United Institute of Medical Sciences, Allahabad",
    "Uttar Pradesh University of Medical Sciences, (Prev. UP Rural Inst.of Med.Sc&R) Etawah",
    "Varun Arjun Medical College, Banthra, Shahjahanpur",
    "Venkateshwara Institute of Medical Sciences, Gajraula",
  ],
  "Uttarakhand": [
    "All India Institute of Medical Sciences, Rishikesh",
    "Doon Medical College, Dehradun, Uttarakhand",
    "Gautam Buddha Chikitsa Mahavidyalaya, Dehradun",
    "Government Medical College (Prev.Uttarakhand Forest Hospital Trust Med.Col.), Haldwani",
    "Himalayan Institute of Medical Sciences, Dehradun",
    "Shri Guru Ram Rai Institute of Medical & Health Sciences, Dehradun",
    "Soban Singh Jeena Government institute of Medical science & Research, Almora",
    "Sridev Suman Subharti Medical College, Dehradun",
    "Veer Chandra Singh Garhwali Govt. Medical Sc. & Research Instt, Srinagar, Pauri Garhwal",
  ],
  "West Bengal": [
    "All India Institute of Medical Sciences, Kalyani, Nadia",
    "Bankura Sammilani Medical College, Bankura",
    "Barasat Government Medical College and Hospital",
    "Burdwan Medical College, Burdwan",
    "Calcutta National Medical College, Kolkata",
    "College of Medicine and JNM Hospital,Kalyani,Nadia",
    "College of Medicine and Sagore Dutta Hospital, Kolkata",
    "Coochbehar Government Medical College & Hospital, Coochbehar, WB",
    "Deben Mahata Government Medical College & Hospital",
    "Diamond Harbour Government Medical College and Hospital, West Bengal",
    "Employees State Insurance Corporation Medical College, Joka, Kolkata",
    "Gouri Devi Institute of Medical Sciences and Hospital, Durgapur",
    "ICARE Institute of Medical Sciences & Research, Haldia, Purba Midanpore",
    "IQ-City Medical College, Burdwan",
    "Institute of Postgraduate Medical Education & Research, Kolkata",
    "JIS School of Medical Science & Research, Howrah",
    "JMN Medical College, Nadia",
    "Jagannath Gupta Institute of Medical Sciences & Hospital, Kolkata",
    "Jalpaiguri Government Medical College and Hospital",
    "Jhargram Government Medical College and Hospital",
    "KPC Medical College,Jadavpur,Kolkata",
    "Malda Medical College & Hospital, Malda",
    "Medical College, Kolkata",
    "Midnapore Medical College, Midnapore",
    "Murshidabad Medical College & Hospitals, Murshidabad",
    "Nilratan Sircar Medical College, Kolkata",
    "North Bengal Medical College, Darjeeling",
    "Prafulla Chandra Sen Government Medical College",
    "RG Kar Medical College, Kolkata",
    "Raiganj Government Medical College & Hospital, Raiganj",
    "Rampurhat Government Medical College & Hospital, Rampurhat",
    "Santiniketan Medical College, Bolpur, West Bengal",
    "Sarat Chandra Chattopadhyay Government Medical College & Hospital, Uluberia",
    "Shri Ramkrishna Institute of Medical Sciences & Sanaka Hospitals, Durgapur",
    "Tamralipto Government Medical College & Hospital",
  ],
};

/** Sorted list of all available states */
export const STATES = Object.keys(COLLEGES_BY_STATE).sort();
